name: path filterde by dorny/paths-filter@v3 instead of "on" attribute 

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_need_to_run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      need_to_run_lint_and_test: ${{ steps.check_files_changed.outputs.changed == 'true' }}
    steps:
      - name: check pull request file changes
        uses: dorny/paths-filter@v3
        id: check_files_changed
        with:
          filters: |
            changed:
              - test/**

  example_execution:
    runs-on: ubuntu-latest
    needs: check_need_to_run

    steps:
    - name: execute echo
      run: echo "workflow executed!!"
