name: Test venv

on: [push]

jobs:
  test_venv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Create venv
      run: python -m venv .venv && source .venv/bin/activate && pip install tqdm

    - name: Check exsisting python3.11  
      run: cd .venv/lib/python3.11 && cd ../../../
    - name: Check exsisting python3.9
      run: cd .venv/lib/python3.9
